stages:
  - build
  - deploy

build:
  stage: build
  only:
    refs:
      - main
  tags:
    - server
  script:
    - echo "Start Build"
    - cd backend
    - chmod +x mvnw
    - pwd
    - ./mvnw clean package
    - pwd
    - ls
    - ls target
    - cd ..
    - mkdir -p /app
    - cp backend/target/backend-0.0.1-SNAPSHOT.jar /app/

deploy:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - server
  script:
    - echo 'Start deploy'
    - pwd
    - ls
    - docker-compose down
    - cd backend
    - pwd
    - ls
#    - ls target
#    - docker build -t backend ./backend
    - docker-compose up -d
    - docker-compose ps
