stages:
  - build
  - deploy

build:
  stage: build
  only:
    refs:
      - main
  tags:
    - server
  script:
    - echo "Start Build"
    - cd ./backend
    - ./mvnw clean package

deploy:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - server
  script:
    - echo 'Start deploy'
    - cd /web/server-app
    - docker-compose down
    - docker-compose up -d
    - docker-compose ps
