version: '3.3'

services:
  backend:
    image: backend
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
    networks:
      - reservation
  frontend:
    image: frontend
    restart: always
    ports:
      - '80:80'
    expose:
      - 80
    networks:
      - reservation
  postgres:
    image: postgres:16rc1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=reservation
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - reservation

networks:
  reservation:
    driver: bridge

volumes:
  db:
    driver: local